### ISSUE TITLE
Dose this still work with the newest game versions

### ISSUE THREAD

**Issue by snowy6409** [mcmonkey4eva/Builder#2]
Dose this still work with the newest 1.12.2 version or dose it need some other supporting thing like the payed version of citizens?

**Comment by mcmonkey4eva** [comment]
All versions of Citizens are free. The Spigot page is a donation option.
It should be compatible with an up-to-date server (though few guarantees are given regarding full functionality, as this is just a forward-porting of an older plugin)
You can download from http://ci.citizensnpcs.co/job/Builder/

**Comment by snowy6409** [comment]
@mcmonkey4eva it throws a null error whenever I try the excavate command or the build command.

`[05:22:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'builder' in plugin Builder v0.9.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/Block
        at net.jrbudda.builder.EmptyBuildBlock.getMat(EmptyBuildBlock.java:19) ~[?:?]
        at net.jrbudda.builder.BuilderSchematic.BuildQueue(BuilderSchematic.java:61) ~[?:?]
        at net.jrbudda.builder.BuilderTrait.GetMatsList(BuilderTrait.java:257) ~[?:?]
        at net.jrbudda.builder.Builder.onCommand(Builder.java:499) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.Block
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at net.jrbudda.builder.EmptyBuildBlock.getMat(EmptyBuildBlock.java:19) ~[?:?]
        at net.jrbudda.builder.BuilderSchematic.BuildQueue(BuilderSchematic.java:61) ~[?:?]
        at net.jrbudda.builder.BuilderTrait.GetMatsList(BuilderTrait.java:257) ~[?:?]
        at net.jrbudda.builder.Builder.onCommand(Builder.java:499) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
        ... 15 more`

**Comment by mcmonkey4eva** [comment]
You are not running the version provided at the link I sent above.
I linked a v1.0 Builder jar, you are running a v0.9.1 Builder jar.
